#!/bin/bash

# 01. Get the list of the network interfaces of the machine without displaying any detail
# for these interfaces. Only the list of names.

# 01. Poluchite spisok setevyh interfejsov mashiny, ne otobrazhaya nikakih detalej dlya
# etih interfejsov. Tol'ko spisok imen.

ifconfig -l
