#!/bin/bash

# 07. Query an external DNS server on the slash16.org domain name (ie.: google 8.8.8.8)

# 07. Zaprosit' vneshnij DNS-server po domennomu slash16.org (t.e. google 8.8.8.8)

nslookup slash16.org 8.8.8.8
