#!/bin/bash

# 20. List all existing users on the VM

# 20. Spisok vsekh sushchestvuyushchikh polzovateley na virtualnoy mashine

cut -f1 -d: /etc/passwd

#### variants 1, 2 & 3
# awk -F: '{ print $1 }' /etc/passwd
# cat /etc/passwd | cut -f1 -d:
# cat /etc/passwd | awk -F: '{print $ 1}'


