#!/bin/bash

# 01. Write a script which displays only the login, UID and Path of each entry of the /etc/passwd file

# 01. Napishite skript, kotoryy otobrazhayet tolko login, UID & Path dlya kazhdoy zapisi v /etc/passwd

cut -d ":" -f1,3,6 /etc/passwd | tr ":" " " | column -t

# column -t -- dlia krasivogo viravnivania

# variant 2:
# cat /etc/passwd | cut -d ":" -f1,3,6 | tr ":" " " | column -t

# variant 3:
# cat /etc/passwd | awk -F':' '{print $1 " " $3 " " $6}' | column -t
